### ISSUE TITLE
Picture tag with source doesn't work

### ISSUE THREAD

**Issue by js-writer** [bloomreach/hippo-ckeditor#1]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. In hippo/blomreach document use ckeditor and choose source. 
2. Type for example
`<picture><source media="(min-width: 800px)" srcset="https://www.euroflorist.pl/img/300x/_big800@pl/BOU20_33.jpg" /> <img alt="" src="https://www.euroflorist.pl/img/300x/_big800@pl/BOU20_33.jpg" /></picture>` 
3. And then when you click save, ckeditor will change `<picture><source>` into `<picture><audio><source>`

### Expected result

*What is the expected result of the above steps?*
Don't wrap source tag with audio in picture tag

### Actual result

*What is the actual result of the above steps?*
Changing `<picture><source>` into `<picture><audio><source>`

## Other details

Settings for my hippo/bloomreach component:
ckeditor.config.overlayed.json: '{allowedContent: true}'
htmlprocessor.id: no-filter
* hippo/bloomreach version: 12.9.25
* Browser: chrome
* OS: windows 10
* CKEditor version: 4.16.0-h2
* Installed CKEditor plugins: image, image2,

Before save:

![image](https://user-images.githubusercontent.com/5675915/196157648-f8e5f49f-1a96-49a2-bf8f-2d44bb9e4f06.png)

After save:

![image](https://user-images.githubusercontent.com/5675915/196157696-bfb583be-ba97-453c-9253-639fc904eedf.png)

**Comment by jeroenhoffman** [comment]
Closing this stale issue. 

Proper way to get traction on this, if still needed, is through support.bloomreach.com. It probably has to do with configuration or with how Bloomreach Content uses CKEditor, not with CKEditor itself.
